[vendor]
name = "The Infinity's"
id = "org.infinite"
url = "https://github.com/The-Infinitys/xross-bass-amp"
au_manufacturer = "INFI"

[[plugin]]
name = "XrossBassAmp"
bundle_id = "xrossbassamp"
crate = "xross-bass-amp"
category = "effect"
fourcc = "XGRA"
au_tag = "Effects"
